version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: staffdev-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 26121999
      POSTGRES_DB: staffdev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: